name: Validate

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Linter
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18.x"
          cache: "yarn"
      - run: yarn
      - run: yarn validate:eslint

  tsc:
    runs-on: ubuntu-latest
    name: TypeScript
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18.x"
          cache: "yarn"
      - run: yarn
      - run: yarn validate:typescript